POST http://localhost:3333/transactions
Content-Type: application/json


{
 "title" : "raparigas",
 "amount": "1000.400",
 "type":"debit"
}




###

 GET http://localhost:3333/transactions

###

 GET http://localhost:3333/transactions/summary

###

 GET http://localhost:3333/transactions/01998242-4796-72ba-aab3-ec51bda26f47

 
